pub mod config;
mod config_defaults;
mod config_magic_dns;
pub mod control;
pub mod crypto;
pub mod diagnostics;
pub mod join_requests;
pub mod magic_dns;
pub mod nat;
mod network_roster;
mod network_routes;
pub mod node_record;
pub mod paths;
pub mod platform_paths;
pub mod presence;
pub mod relay;
pub mod service_signaling;
pub mod signaling;
pub mod wireguard;

pub use config::DEFAULT_RELAYS;
