#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

export NVPN_EXIT_NODE_E2E_PAID=1
export NVPN_EXIT_NODE_E2E_PAYMENT_MODE=spilman
export NVPN_EXIT_NODE_E2E_SELECTION_MODE=automatic
export NVPN_EXIT_NODE_E2E_PRICE_MSAT_PER_GB="${NVPN_EXIT_NODE_E2E_PRICE_MSAT_PER_GB:-50000}"
export NVPN_EXIT_NODE_E2E_SPILMAN_FREE_PROBE_UNITS="${NVPN_EXIT_NODE_E2E_SPILMAN_FREE_PROBE_UNITS:-1048576}"
export NVPN_EXIT_NODE_E2E_PROJECT_NAME="${NVPN_EXIT_NODE_E2E_PROJECT_NAME:-nostr-vpn-e2e-paid-exit-automatic}"

exec "$SCRIPT_DIR/e2e-exit-node-docker.sh"
